apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP #default type if not set
  ports:
  - name: redis-service
    port: 6379
    targetPort: 6379
  selector:
    app: redis